######################################################################
# Automatically generated by qmake (3.0) Thu Jan 12 13:53:35 2017
######################################################################

TEMPLATE = app
TARGET = ground-system
INCLUDEPATH += .

# Input
HEADERS += roscontroller.h
SOURCES += main.cpp roscontroller.cpp
RESOURCES += qml.qrc
